In [4]:
import numpy as np
from math import gcd

def lcm(a, b):
    """Calculate the least common multiple of two integers."""
    return (b // gcd(a, b), a // gcd(a, b))

def gaussian_integer_elimination(matrix):
    """Perform Gaussian elimination on the matrix with integer arithmetic."""
    n = matrix.shape[0]
    # Create an augmented matrix [A | I]
    augmented_matrix = np.hstack((matrix, np.eye(n, dtype=int)))

    # Perform Gaussian elimination to transform the matrix into [D | A^-1]
    for i in range(n):
        diag_element = augmented_matrix[i, i]
        # Make the other elements in the current column 0
        for j in range(n):
            if i != j:
                # Compute least common multiple and adjust elements
                lcm_a, lcm_b = lcm(augmented_matrix[j, i], diag_element)
                augmented_matrix[j, :] = (
                    lcm_a * augmented_matrix[j, :] - lcm_b * augmented_matrix[i, :]
                )

    # Return the transformed matrix
    return augmented_matrix

# Example usage
A = np.array([[4, 7, 5], [2, 6, 7], [1, 2, 3]], dtype=int)
result = gaussian_integer_elimination(A)
print(result)


[[ 260    0    0   80 -220  380]
 [   0  130    0   10   70 -180]
 [   0    0   26   -4   -2   20]]
