In [1]:
import numpy as np


In [2]:

def decouper_matrice(matrice):
  """Découpe une matrice en 4 sous-matrices.

  Args:
    matrice: La matrice à découper.

  Returns:
    Un tuple contenant les 4 sous-matrices.
  """
  lignes, colonnes = matrice.shape
  milieu_lignes = lignes // 2
  milieu_colonnes = colonnes // 2

  sous_matrice1 = matrice[:milieu_lignes, :milieu_colonnes]
  sous_matrice2 = matrice[:milieu_lignes, milieu_colonnes:]
  sous_matrice3 = matrice[milieu_lignes:, :milieu_colonnes]
  sous_matrice4 = matrice[milieu_lignes:, milieu_colonnes:]

  return sous_matrice1, sous_matrice2, sous_matrice3, sous_matrice4

# Exemple d'utilisation
matrice = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])

sous_matrice1, sous_matrice2, sous_matrice3, sous_matrice4 = decouper_matrice(matrice)

print("Sous-matrice 1:\n", sous_matrice1)
print("Sous-matrice 2:\n", sous_matrice2)
print("Sous-matrice 3:\n", sous_matrice3)
print("Sous-matrice 4:\n", sous_matrice4)

Sous-matrice 1:
 [[1 2]
 [5 6]]
Sous-matrice 2:
 [[3 4]
 [7 8]]
Sous-matrice 3:
 [[ 9 10]
 [13 14]]
Sous-matrice 4:
 [[11 12]
 [15 16]]


In [3]:
def Trace(x, y):
  """Calcule la trace du produit de deux matrices de manière récursive."""
  if x.shape == (1, 1):  # Check if x is a 1x1 matrix
    return x[0, 0] * y[0, 0]  # Base case: element-wise multiplication
  sous_x0, sous_x1, sous_x2, sous_x3 = decouper_matrice(x)
  sous_y0, sous_y1, sous_y2, sous_y3 = decouper_matrice(y)
  return (Trace(sous_x0, sous_y0) + Trace(sous_x1, sous_y2) +
          Trace(sous_x2, sous_y1) + Trace(sous_x3, sous_y3))


In [4]:
import numpy as np

# ... (decouper_matrice and Trace functions from previous response) ...

def test_trace(size):
  """Tests the Trace function with matrices of given size."""
  x = np.random.rand(size, size)
  y = np.random.rand(size, size)

  # Calculate trace using our function and NumPy's function
  trace_recursive = Trace(x, y)
  trace_numpy = np.trace(x @ y)  # @ is matrix multiplication

  # Compare the results
  print(f"Size: {size}x{size}")
  print(f"Recursive Trace: {trace_recursive}")
  print(f"NumPy Trace: {trace_numpy}")
  print(f"Difference: {abs(trace_recursive - trace_numpy)}\n")

# Test with different matrix sizes
for size in [2, 4, 8, 16]:
  test_trace(size)

Size: 2x2
Recursive Trace: 1.1261555707257724
NumPy Trace: 1.1261555707257722
Difference: 2.220446049250313e-16

Size: 4x4
Recursive Trace: 4.400820457699346
NumPy Trace: 4.400820457699346
Difference: 0.0

Size: 8x8
Recursive Trace: 19.18435021545447
NumPy Trace: 19.18435021545447
Difference: 0.0

Size: 16x16
Recursive Trace: 67.46689529721921
NumPy Trace: 67.46689529721922
Difference: 1.4210854715202004e-14

